name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: make install

      - name: Publish
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
