name: Publish demo Jaffle Shop on Github Pages

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./example_jaffle_shop

jobs:
  build_and_deploy_github_pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
          virtualenvs-path: .venv

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: poetry

      - name: Install dependencies
        run: |
          cd ..
          make install
      
      - name: Build Jaffle Shop dbt docs
        run: |
          source ../.venv/bin/activate
          poetry run dbt-diagrams docs generate --static

      - name: Rename static_index.html to index.html
        run: mv ./target/static_index.html ./target/index.html

      - name: Push docs folder to github-pages branch.
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./example_jaffle_shop/target"
          keep_files: true
          publish_branch: github-pages
