name: Publish demo Jaffle Shop on Github Pages

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./example_jaffle_shop

jobs:
  build_and_deploy_github_pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pip3 install poetry==1.6.1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry
      
      - name: Install dependencies
        run: poetry install
      
      - name: Build Jaffle Shop dbt docs
        run: poetry run dbt docs generate --static

      - name: Rename static_index.html to index.html
        run: mv ./target/static_index.html ./target/index.html
      
      - name: Push docs folder to github-pages branch.
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./example_jaffle_shop/target"
          keep_files: true
          publish_branch: github-pages

